---
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topics-job
  namespace: staging
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: kafka-topics-creator
        image: confluentinc/cp-kafka:7.5.0
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - |
          kafka-topics --create --topic directories-to-scan --partitions 60 --replication-factor 3 --config min.insync.replicas=2 --bootstrap-server kafka-0.kafka-headless.staging.svc.cluster.local:9092 && \
          kafka-topics --create --topic files-to-scan --partitions 50 --replication-factor 3 --config min.insync.replicas=2 --bootstrap-server kafka-0.kafka-headless.staging.svc.cluster.local:9092 && \
          kafka-topics --create --topic scan-results --partitions 50 --replication-factor 3 --config min.insync.replicas=2 --bootstrap-server kafka-0.kafka-headless.staging.svc.cluster.local:9092 && \
          kafka-topics --create --topic empty-result-topic --partitions 50 --replication-factor 3 --config min.insync.replicas=2 --bootstrap-server kafka-0.kafka-headless.staging.svc.cluster.local:9092 && \
          kafka-topics --create --topic small-result-topic --partitions 50 --replication-factor 3 --config min.insync.replicas=2 --bootstrap-server kafka-0.kafka-headless.staging.svc.cluster.local:9092 && \
          kafka-topics --create --topic medium-result-topic --partitions 50 --replication-factor 3 --config min.insync.replicas=2 --bootstrap-server kafka-0.kafka-headless.staging.svc.cluster.local:9092 && \
          kafka-topics --create --topic large-result-topic --partitions 50 --replication-factor 3 --config min.insync.replicas=2 --bootstrap-server kafka-0.kafka-headless.staging.svc.cluster.local:9092 && \
          kafka-topics --create --topic scan-directories-count --partitions 1 --replication-factor 3 --config min.insync.replicas=2 --bootstrap-server kafka-0.kafka-headless.staging.svc.cluster.local:9092 && \
          kafka-topics --create --topic scan-files-count --partitions 1 --replication-factor 3 --config min.insync.replicas=2 --bootstrap-server kafka-0.kafka-headless.staging.svc.cluster.local:9092 && \
          kafka-topics --create --topic completed-directories-count --partitions 1 --replication-factor 3 --config min.insync.replicas=2 --bootstrap-server kafka-0.kafka-headless.staging.svc.cluster.local:9092 && \
          kafka-topics --create --topic completed-files-count --partitions 1 --replication-factor 3 --config min.insync.replicas=2 --bootstrap-server kafka-0.kafka-headless.staging.svc.cluster.local:9092
