{
 "title": "ftp_dashboard1",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "file scanner received messages total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(__name__) (file_scanner_received_messages_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "file_scanner_received_messages_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(__name__) (rate(file_scanner_received_messages_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "file_scanner_download_duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(le) (rate(file_scanner_download_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "file_scanner_saving_duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(le) (rate(file_scanner_saving_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "file_scanner_scanned_duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(le) (rate(file_scanner_scan_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "file_scanner_scanned_files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(__name__) (file_scanner_scanned_files_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "file_scanner_sended_files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by(__name__) (file_scanner_sended_files_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "file_scanner_completed_files_counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(__name__) (file_scanner_completed_files_sent_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "file_scanner_returned_files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum by(__name__) (file_scanner_returned_files_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "file_scanner_errors_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 48 },
   "targets": [
    { "expr": "sum(file_scanner_errors_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "directory lister received messages total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by(__name__) (directory_lister_received_messages_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "directory_lister_received_messages_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(directory_lister_received_messages_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "directory_lister_ftp_listing_duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum by(le) (rate(directory_lister_ftp_list_directory_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "directory lister files fount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum by(__name__) (directory_lister_files_found_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "directory lister directories processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "sum by(__name__) (directory_lister_directories_processed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "directory lister sent files to topic total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "sum by(__name__) (directory_lister_kafka_messages_sent_scan_files_count_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "directory lister scan directories count ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "sum by(__name__) (directory_lister_kafka_messages_sent_scan_dirs_count_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "directory lister completed directories count ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(__name__) (directory_lister_kafka_messages_sent_completed_dirs_count_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "scan files reducer received numbers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(counter_reducer_received_numbers_total{pod=~\"counter-reducer-scan-files.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "scan directories reducer received numbers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(counter_reducer_received_numbers_total{pod=~\"counter-reducer-scan-directories.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "completed files reducer received numbers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(counter_reducer_received_numbers_total{pod=~\"counter-reducer-completed-files.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "scan directories reducer received numbers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(counter_reducer_received_numbers_total{pod=~\"counter-reducer-completed-directories.*\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}