// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/grpc/proto/get-report-service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetReportService_GetDirectory_FullMethodName = "/report.GetReportService/GetDirectory"
)

// GetReportServiceClient is the client API for GetReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис: единый метод для получения любой директории
type GetReportServiceClient interface {
	GetDirectory(ctx context.Context, in *DirectoryRequest, opts ...grpc.CallOption) (*DirectoryResponse, error)
}

type getReportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetReportServiceClient(cc grpc.ClientConnInterface) GetReportServiceClient {
	return &getReportServiceClient{cc}
}

func (c *getReportServiceClient) GetDirectory(ctx context.Context, in *DirectoryRequest, opts ...grpc.CallOption) (*DirectoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DirectoryResponse)
	err := c.cc.Invoke(ctx, GetReportService_GetDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetReportServiceServer is the server API for GetReportService service.
// All implementations must embed UnimplementedGetReportServiceServer
// for forward compatibility.
//
// Сервис: единый метод для получения любой директории
type GetReportServiceServer interface {
	GetDirectory(context.Context, *DirectoryRequest) (*DirectoryResponse, error)
	mustEmbedUnimplementedGetReportServiceServer()
}

// UnimplementedGetReportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetReportServiceServer struct{}

func (UnimplementedGetReportServiceServer) GetDirectory(context.Context, *DirectoryRequest) (*DirectoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDirectory not implemented")
}
func (UnimplementedGetReportServiceServer) mustEmbedUnimplementedGetReportServiceServer() {}
func (UnimplementedGetReportServiceServer) testEmbeddedByValue()                          {}

// UnsafeGetReportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetReportServiceServer will
// result in compilation errors.
type UnsafeGetReportServiceServer interface {
	mustEmbedUnimplementedGetReportServiceServer()
}

func RegisterGetReportServiceServer(s grpc.ServiceRegistrar, srv GetReportServiceServer) {
	// If the following call pancis, it indicates UnimplementedGetReportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetReportService_ServiceDesc, srv)
}

func _GetReportService_GetDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetReportServiceServer).GetDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetReportService_GetDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetReportServiceServer).GetDirectory(ctx, req.(*DirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetReportService_ServiceDesc is the grpc.ServiceDesc for GetReportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetReportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "report.GetReportService",
	HandlerType: (*GetReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDirectory",
			Handler:    _GetReportService_GetDirectory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc/proto/get-report-service.proto",
}
