// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/grpc/proto/get-report-service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectoryRequest) Reset() {
	*x = DirectoryRequest{}
	mi := &file_api_grpc_proto_get_report_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryRequest) ProtoMessage() {}

func (x *DirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_get_report_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryRequest.ProtoReflect.Descriptor instead.
func (*DirectoryRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_get_report_service_proto_rawDescGZIP(), []int{0}
}

func (x *DirectoryRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *DirectoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Описание результата сканирования файла
type ScanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResult) Reset() {
	*x = ScanResult{}
	mi := &file_api_grpc_proto_get_report_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResult) ProtoMessage() {}

func (x *ScanResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_get_report_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResult.ProtoReflect.Descriptor instead.
func (*ScanResult) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_get_report_service_proto_rawDescGZIP(), []int{1}
}

func (x *ScanResult) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ScanResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// Описание файла
type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	ScanResults   []*ScanResult          `protobuf:"bytes,2,rep,name=ScanResults,proto3" json:"ScanResults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_api_grpc_proto_get_report_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_get_report_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_get_report_service_proto_rawDescGZIP(), []int{2}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetScanResults() []*ScanResult {
	if x != nil {
		return x.ScanResults
	}
	return nil
}

// Описание директории
type Directory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directory     string                 `protobuf:"bytes,1,opt,name=Directory,proto3" json:"Directory,omitempty"`
	Subdirectory  []*Directory           `protobuf:"bytes,2,rep,name=Subdirectory,proto3" json:"Subdirectory,omitempty"`
	Files         []*File                `protobuf:"bytes,3,rep,name=Files,proto3" json:"Files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Directory) Reset() {
	*x = Directory{}
	mi := &file_api_grpc_proto_get_report_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Directory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Directory) ProtoMessage() {}

func (x *Directory) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_get_report_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Directory.ProtoReflect.Descriptor instead.
func (*Directory) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_get_report_service_proto_rawDescGZIP(), []int{3}
}

func (x *Directory) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *Directory) GetSubdirectory() []*Directory {
	if x != nil {
		return x.Subdirectory
	}
	return nil
}

func (x *Directory) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

// Ответ: scan_id + нужная Directory
type DirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Directory     *Directory             `protobuf:"bytes,2,opt,name=Directory,proto3" json:"Directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectoryResponse) Reset() {
	*x = DirectoryResponse{}
	mi := &file_api_grpc_proto_get_report_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryResponse) ProtoMessage() {}

func (x *DirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_get_report_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryResponse.ProtoReflect.Descriptor instead.
func (*DirectoryResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_get_report_service_proto_rawDescGZIP(), []int{4}
}

func (x *DirectoryResponse) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *DirectoryResponse) GetDirectory() *Directory {
	if x != nil {
		return x.Directory
	}
	return nil
}

var File_api_grpc_proto_get_report_service_proto protoreflect.FileDescriptor

const file_api_grpc_proto_get_report_service_proto_rawDesc = "" +
	"\n" +
	"'api/grpc/proto/get-report-service.proto\x12\x06report\"?\n" +
	"\x10DirectoryRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x12\n" +
	"\x04Path\x18\x02 \x01(\tR\x04Path\"8\n" +
	"\n" +
	"ScanResult\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\tR\x04Type\x12\x16\n" +
	"\x06Result\x18\x02 \x01(\tR\x06Result\"P\n" +
	"\x04File\x12\x12\n" +
	"\x04Path\x18\x01 \x01(\tR\x04Path\x124\n" +
	"\vScanResults\x18\x02 \x03(\v2\x12.report.ScanResultR\vScanResults\"\x84\x01\n" +
	"\tDirectory\x12\x1c\n" +
	"\tDirectory\x18\x01 \x01(\tR\tDirectory\x125\n" +
	"\fSubdirectory\x18\x02 \x03(\v2\x11.report.DirectoryR\fSubdirectory\x12\"\n" +
	"\x05Files\x18\x03 \x03(\v2\f.report.FileR\x05Files\"]\n" +
	"\x11DirectoryResponse\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12/\n" +
	"\tDirectory\x18\x02 \x01(\v2\x11.report.DirectoryR\tDirectory2W\n" +
	"\x10GetReportService\x12C\n" +
	"\fGetDirectory\x12\x18.report.DirectoryRequest\x1a\x19.report.DirectoryResponseB\x11Z\x0f/api/grpc/protob\x06proto3"

var (
	file_api_grpc_proto_get_report_service_proto_rawDescOnce sync.Once
	file_api_grpc_proto_get_report_service_proto_rawDescData []byte
)

func file_api_grpc_proto_get_report_service_proto_rawDescGZIP() []byte {
	file_api_grpc_proto_get_report_service_proto_rawDescOnce.Do(func() {
		file_api_grpc_proto_get_report_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_proto_get_report_service_proto_rawDesc), len(file_api_grpc_proto_get_report_service_proto_rawDesc)))
	})
	return file_api_grpc_proto_get_report_service_proto_rawDescData
}

var file_api_grpc_proto_get_report_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_grpc_proto_get_report_service_proto_goTypes = []any{
	(*DirectoryRequest)(nil),  // 0: report.DirectoryRequest
	(*ScanResult)(nil),        // 1: report.ScanResult
	(*File)(nil),              // 2: report.File
	(*Directory)(nil),         // 3: report.Directory
	(*DirectoryResponse)(nil), // 4: report.DirectoryResponse
}
var file_api_grpc_proto_get_report_service_proto_depIdxs = []int32{
	1, // 0: report.File.ScanResults:type_name -> report.ScanResult
	3, // 1: report.Directory.Subdirectory:type_name -> report.Directory
	2, // 2: report.Directory.Files:type_name -> report.File
	3, // 3: report.DirectoryResponse.Directory:type_name -> report.Directory
	0, // 4: report.GetReportService.GetDirectory:input_type -> report.DirectoryRequest
	4, // 5: report.GetReportService.GetDirectory:output_type -> report.DirectoryResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_grpc_proto_get_report_service_proto_init() }
func file_api_grpc_proto_get_report_service_proto_init() {
	if File_api_grpc_proto_get_report_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_proto_get_report_service_proto_rawDesc), len(file_api_grpc_proto_get_report_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_proto_get_report_service_proto_goTypes,
		DependencyIndexes: file_api_grpc_proto_get_report_service_proto_depIdxs,
		MessageInfos:      file_api_grpc_proto_get_report_service_proto_msgTypes,
	}.Build()
	File_api_grpc_proto_get_report_service_proto = out.File
	file_api_grpc_proto_get_report_service_proto_goTypes = nil
	file_api_grpc_proto_get_report_service_proto_depIdxs = nil
}
