file_scanner_service:
  kafka_consumer:
    brokers:
      - "localhost:9092"
    consumer_topic: "files-to-scan"
    consumer_group: "file-scanner-group"
  kafka_scan_result_producer:
    broker: "localhost:9092"
    file_scan_download_path: "/home/k0vd3n/tmp"
    permission: "0755"
    scanner_types: ["zero_bytes"]
    routing:
      default_topic: "scan-results"
      rules:
        - scan_type: "zero_bytes"
          trigger_value: "0"
          output_topics: ["empty-result-topic"]
        - scan_type: "zero_bytes" 
          trigger_value: "0-256"
          output_topics: ["small-result-topic"]
        - scan_type: "zero_bytes"
          trigger_value: "256-512"
          output_topics: ["medium-result-topic"]
        - scan_type: "zero_bytes"
          trigger_value: "512-"
          output_topics: ["large-result-topic"]
  kafka_completed_files_count_producer:
    broker: "localhost:9092"
    completed_files_count_topic: "completed-files-count"
  mongo:
    mongo_uri: "mongodb://testuser:testpassword@localhost:27017/?authSource=admin"
    mongo_db: "testdb"
    mongo_collection: "metrics" 
  metrics:
    instance: "instance"
    prom_http_port: ":2112"
    push_gateway:
      url: "localhost:9091"
      job_name: "file_scanner_service"
      instance: "file_scanner_service"
  max_retries: 5
  timeout_seconds: 120

directory_lister_service:
  kafka:
    broker: "localhost:9092"
    consumer_topic: "directories-to-scan"
    consumer_group: "dir-lister-group"
    directories_to_scan_topic: "directories-to-scan"
    scan_directories_count_topic: "scan-directories-count"
    files_to_scan_topic: "files-to-scan"
    scan_files_count_topic: "scan-files-count"
    completed_directories_count_topic: "completed-directories-count"
    max_retries: 5
    timeout_seconds: 60
  metrics:
    instance: "instance"
    prom_http_port: ":2112"
  # jaeger:
  #   service_name: "directory_lister_service"
  #   agent_host: "localhost"
  #   agent_port: "6831"
  #   sampler:
  #     type: const
  #     param: 1
  #   reporter:
  #     log_spans: true

main_service:
  kafka:
    broker: "localhost:9092"
    directory_topic: "directories-to-scan"
  grpc:
    report_server_address: "localhost"
    report_server_port: ":50051"
    status_server_address: "localhost"
    status_server_port: ":50053"
  http:
    port: ":8080"
  metrics:
    instance: "instance"
    prom_http_port: ":2112"

counter_reducer_service:
  kafka:
    brokers:
      - "localhost:9092"
    counter_reducer_topic: "scan-directories-count"
    counter_reducer_group: "scan-directories-count-counter-reducer-group"
    batch_size: 1000
    duration: 15
  mongo:
    mongo_uri: "mongodb://testuser:testpassword@localhost:27017/?authSource=admin"
    mongo_db: "testdb"
    mongo_collection: "scan_directories_count"
  metrics:
    instance: "instance"
    prom_http_port: ":2112"

scan_result_reducer_service:
  kafka:
    brokers:
      - "localhost:9092"
    consumer_topic: "scan-results"
    consumer_group: "scan-results-reducer-consumer-group"
    batch_size: 1000
    duration: 15
  mongo:
    mongo_uri: "mongodb://testuser:testpassword@localhost:27017/?authSource=admin"
    mongo_db: "testdb"
    mongo_collection: "scan_reports"
  metrics:
    instance: "instance"
    prom_http_port: ":2112"

report_service:
  mongo: 
    mongo_uri: "mongodb://testuser:testpassword@localhost:27017/?authSource=admin"
    mongo_db: "testdb"
    mongo_collection: "scan_reports"
  grpc:
    server_port: ":50051"
  repository:
    directory: "/home/k0vd3n/go/src/ftp-scanner_try2/reports"
  metrics:
    instance: "instance"
    prom_http_port: ":2112"

status_service: 
  mongo:
    mongo_uri: "mongodb://testuser:testpassword@localhost:27017/?authSource=admin"
    mongo_db: "testdb"
    scan_directories_count_collection: "scan_directories_count"
    scan_files_count_collection: "scan_files_count"
    completed_directories_count_collection: "completed_directories_count"
    completed_files_count_collection: "completed_files_count"
  grpc:
    port: ":50053"
  metrics:
    instance: "instance"
    prom_http_port: ":2112"

push_gateway:
  url: "http://localhost:9091"
  job_name: "main-service"
  instance: "scan_result_reducer-service"
  push_interval: 20

