routing:
  default_topic: "scan-results"
  rules:
    - scan_type: "zero_bytes"
      trigger_value: "0"
      output_topics: ["empty-result-topic"]
    
    - scan_type: "zero_bytes"
      trigger_value: "0-256"
      output_topics: ["small-result-topic"]
    
    - scan_type: "zero_bytes"
      trigger_value: "256-512"
      output_topics: ["medium-result-topic"]
    
    - scan_type: "zero_bytes"
      trigger_value: "512-"
      output_topics: ["large-result-topic"]